import { SOCIAL_IMAGES_URL } from './constants.v5.js';

export const socials = {
  telegram: {
    name: 'Телеграм',
    img: `${SOCIAL_IMAGES_URL}/telegram-icon.svg`,
    shortList: {
      full: [
        {
          type: 'Подписчики followers',
          id: 747,
          name: 'TG Подписчики РФ Живые + Онлайн + Топ⭐⭐⭐',
          cost: '3500.00',
          guarantee: '+',
          timetostart: '24 ч',
          speed: 'до 1000 в сутки',
          description: [
            '🔹 Живые русские Телеграм подписчики с онлайном',
            '⭐ Эксклюзивная услуга',
            '🤵 Качество: реальные аккаунты русских пользователей',
            '✅ Безопасная накрутка',
            '🌍 ГЕО: РФ аккаунты',
            '⌛️ Запуск услуги: до 24 часов',
            '🚀 Скорость: до 1000 в сутки',
          ],
          information: [
            '🔹 Способствуют выводу канала в ТОП поиска',
            '🔹 Подписываются реальные люди, которые ежедневно выходят в онлайн, что полезно для групп, где видно число пользователей в онлайне',
            '🔹 Подписываются реальные живые люди, которые могут проявлять активность',
            '🔹 Запрещено накручивать 18+ группы, содержащие запрещенный контент, политику, оружие, пирамиды, казино и другие запрещенные темы',
            '🔹 Статус заказа может не обновляться, так как услуга выполняется вручную',
          ],
          example: `Пример: https://t.me/channelname. Заказы по реферальной ссылке могут отменяться. Для реферальных ссылок рекомендуем пользоваться этой услугой: 393. Накрутка на рекламные посты`,
        },
        {
          type: 'Подписчики followers',
          id: 761,
          name: 'TG Подписчики РФ #4 [Без Отписок, РУ номера]⭐⭐⭐',
          cost: '320.00',
          guarantee: '+',
          timetostart: '1 ч',
          speed: 'до 5000 в сутки',
          description: [],
          information: '',
        },
        {
          type: 'Подписчики followers',
          id: 787,
          name: 'TG Подписчики РФ Офферные + Онлайн + Топ⭐⭐⭐',
          cost: '1150.00',
          guarantee: '+',
          timetostart: '1 ч',
          speed: 'до 3000 в сутки',
          description: [],
          information: '',
        },
        {
          type: 'Подписчики followers',
          id: 545,
          name: 'TG Подписчики [Гарантия 30 дней]♻️',
          cost: '80.00',
          guarantee: '+',
          timetostart: '24 ч',
          speed: 'до 5000 в сутки',
          description: [],
          information: '',
        },
        {
          type: 'Просмотры views',
          id: 708,
          name: 'TG Просмотры [Рандом]',
          cost: '0.30',
          guarantee: '+',
          timetostart: '5 мин',
          speed: 'до 100000 в час',
          description: [],
          information: '',
        },
        {
          type: 'Просмотры views',
          id: 659,
          name: 'TG Просмотры на любой пост РФ #2 [Мгновенные]⭐',
          cost: '1.80',
          guarantee: '+',
          timetostart: '5 мин',
          speed: 'до 10000 в час',
          description: [],
          information: '',
        },
        {
          type: 'Просмотры views',
          id: 719,
          name: 'TG Подписка на Просмотры (Будущие + Старые посты)',
          cost: '0.78',
          guarantee: '+',
          timetostart: '5 мин',
          speed: 'до 20000 в час',
          description: [],
          information: '',
        },
        {
          type: 'Реакции reactions',
          id: 832,
          name: 'Реакции на пост (👍,❤️,🔥,🥰,👏,😁,🎉,🤩) [Быстрый Старт]',
          cost: '5.00',
          guarantee: '+',
          timetostart: '5 мин',
          speed: 'до 5000 в сутки',
          description: [],
          information: '',
        },
        {
          type: 'Голосование polls',
          id: 566,
          name: 'TG Голоса в опрос',
          cost: '40.00',
          guarantee: '+',
          timetostart: '12 ч',
          speed: 'до 50000 в сутки',
          description: [],
          information: '',
        },
      ],
    },
    services: {
      autoviews: {
        cost: 1,
        amount: 1000,
      },
      reactions: {
        cost: 4,
        amount: 1000,
        full: [
          {
            id: 869,
            name: 'Реакции на пост (👍,❤️,🔥,🥰,👏,😁,🎉,🤩)',
            cost: '3.00',
            guarantee: '+',
            timetostart: '1 час',
            speed: 'до 1000 в час',
            description: [],
            information: '',
          },
          {
            id: 580,
            name: 'Premium Реакции на пост (👌 😍 ❤️ 🤡 👍 🐳)',
            cost: '3.65',
            guarantee: '+',
            timetostart: '1 час',
            speed: 'до 1000 в час',
            description: [],
            information: '',
          },
          {
            id: 714,
            name: 'Реакции на пост (👎 😱 💩 😢 🤮)',
            cost: '3.65',
            guarantee: '+',
            timetostart: '1 час',
            speed: 'до 1000 в час',
            description: [],
            information: '',
          },
        ],
      },
      reposts: {
        cost: 34,
        amount: 1000,
        full: [
          {
            id: 237,
            name: 'TG Репосты RU + Статистика',
            cost: '35.00',
            guarantee: '+',
            timetostart: '24 ч',
            speed: 'до 5000 в сутки',
            description: [],
            information: '',
          },
        ],
      },
      comments: {
        cost: 3,
        amount: 1,
        full: [
          {
            id: 237,
            name: 'TG Умные Комментарии🌱',
            cost: '3000.00',
            guarantee: '+',
            timetostart: '24 ч',
            speed: 'до 1000 в сутки',
            description: [],
            information: '',
          },
        ],
      },
      views: {
        cost: 1,
        amount: 1000,
        full: [
          {
            id: 640,
            name: 'TG Подписка на Просмотры [30 дней] RU - плавные⭐⭐⭐',
            cost: '399.00',
            guarantee: '+',
            timetostart: '5 мин',
            speed: 'до 200000 в сутки',
            description: [],
            information: '',
          },
          {
            id: 708,
            name: 'TG Просмотры [Рандом]',
            cost: '0.30',
            guarantee: '+',
            timetostart: '5 мин',
            speed: 'до 100000 в час',
            description: [],
            information: '',
          },
          {
            id: 659,
            name: 'TG Просмотры на любой пост РФ #2 [Мгновенные]⭐',
            cost: '1.80',
            guarantee: '+',
            timetostart: '5 мин',
            speed: 'до 10000 в час',
            description: [],
            information: '',
          },
          {
            id: 713,
            name: 'TG Просмотры [Плавное добавление] 🔞 - без ограничений по тематике⭐⭐⭐🌱',
            cost: '3.00',
            guarantee: '+',
            timetostart: '5 мин',
            speed: 'до 300 в час',
            description: [],
            information: '',
          },
          {
            id: 750,
            name: 'TG Живые Просмотры РФ (🇷🇺) + Статистика + ТОП⭐⭐⭐',
            cost: '3.75',
            guarantee: '+',
            timetostart: '5 мин',
            speed: 'до 10000 в час',
            description: [],
            information: '',
          },
        ],
      },
      followers: {
        cost: 40,
        amount: 1000,
        full: [
          {
            id: 747,
            name: 'TG Подписчики РФ Живые + Онлайн + Топ⭐⭐⭐',
            cost: '3500.00',
            guarantee: '+',
            timetostart: '24 ч',
            speed: 'до 1000 в сутки',
            description: [],
            information: '',
          },
          {
            id: 761,
            name: 'TG Подписчики РФ #4 [Без Отписок, РУ номера]⭐⭐⭐',
            cost: '320.00',
            guarantee: '+',
            timetostart: '1 ч',
            speed: 'до 5000 в сутки',
            description: [],
            information: '',
          },
          {
            id: 787,
            name: 'TG Подписчики РФ Офферные + Онлайн + Топ⭐⭐⭐',
            cost: '1150.00',
            guarantee: '+',
            timetostart: '1 ч',
            speed: 'до 3000 в сутки',
            description: [],
            information: '',
          },
          {
            id: 545,
            name: 'TG Подписчики [Гарантия 30 дней]♻️',
            cost: '80.00',
            guarantee: '+',
            timetostart: '24 ч',
            speed: 'до 5000 в сутки',
            description: [],
            information: '',
          },
          {
            id: 210,
            name: 'TG Подписчики РФ + Аватарки #2⭐⭐',
            cost: '125.00',
            guarantee: '+',
            timetostart: '24 ч',
            speed: 'до 10000 в сутки',
            description: [],
            information: '',
          },
          {
            id: 529,
            name: 'TG Подписчики #1 [Без отписок]⭐⭐⭐',
            cost: '180.00',
            guarantee: '+',
            timetostart: '5 мин',
            speed: 'до 20000 в сутки',
            description: [],
            information: '',
          },
        ],
      },
      autolikes: {
        cost: 4,
        amount: 1000,
      },
      polls: {
        cost: 32,
        amount: 1000,
        full: [
          {
            id: 566,
            name: 'TG Голоса в опрос',
            cost: '38.00',
            guarantee: '+',
            timetostart: '12 ч',
            speed: 'до 50000 в сутки',
            description: [],
            information: '',
          },
          {
            id: 712,
            name: 'TG голосование в опросах (плавная накрутка)🌱',
            cost: '1990.00',
            guarantee: '+',
            timetostart: '24 ч',
            speed: 'до 1000 в сутки',
            description: [],
            information: '',
          },
        ],
      },
    },
  },
  vk: {
    name: 'Вконтакте',
    img: `${SOCIAL_IMAGES_URL}/vk-icon.svg`,
    services: {
      likes: {
        cost: 45,
        amount: 1000,
      },
      friends: {
        cost: 90,
        amount: 1000,
      },
      listenings: {
        cost: 13,
        amount: 10,
      },
      reposts: {
        cost: 165,
        amount: 1000,
      },
      views: {
        cost: 3.2,
        amount: 1000,
      },
      followers: {
        cost: 90,
        amount: 1000,
      },
      autoviews: {
        cost: 2.5,
        amount: 1000,
      },
      comments: {
        cost: 3,
        amount: 1,
      },
    },
  },
  instagram: {
    name: 'Инстаграмм',
    img: `${SOCIAL_IMAGES_URL}/instagram-icon.svg`,
    services: {
      followers: {
        cost: 12,
        amount: 1000,
      },
      reels: {
        cost: 1.5,
        amount: 1000,
      },
      comments: {
        cost: 3.5,
        amount: 10,
      },
      stories: {
        cost: 15,
        amount: 1000,
      },
      reposts: {
        cost: 13,
        amount: 1000,
      },
      likes: {
        cost: 3,
        amount: 1000,
      },
      autolikes: {
        cost: 3,
        amount: 1000,
      },
      autoreels: {
        cost: 1.5,
        amount: 1000,
      },
      coverages: {
        cost: 5,
        amount: 1000,
      },
      conservations: {
        cost: 6,
        amount: 1000,
      },
    },
  },
  tiktok: {
    name: 'ТикТок',
    img: `${SOCIAL_IMAGES_URL}/tiktok-icon.svg`,
    services: {
      followers: {
        cost: 260,
        amount: 1000,
      },
      reposts: {
        cost: 21,
        amount: 1000,
      },
      views: {
        cost: 1,
        amount: 1000,
      },
      likes: {
        cost: 59,
        amount: 1000,
      },
      conservations: {
        cost: 31,
        amount: 1000,
      },
    },
  },
  youtube: {
    name: 'Ютуб',
    img: `${SOCIAL_IMAGES_URL}/youtube-icon.svg`,
    services: {
      views: {
        cost: 90,
        amount: 1000,
      },
      followers: {
        cost: 890,
        amount: 1000,
      },
      comments: {
        cost: 780,
        amount: 1000,
      },
      likes: {
        cost: 240,
        amount: 1000,
      },
    },
  },
  twitter: {
    name: 'Твиттер',
    img: `${SOCIAL_IMAGES_URL}/twitter-icon.svg`,
    services: {
      likes: {
        cost: 280,
        amount: 1000,
      },
      retweets: {
        cost: 250,
        amount: 1000,
      },
      followers: {
        cost: 430,
        amount: 1000,
      },
    },
  },
  spotify: {
    name: 'Спотифай',
    img: `${SOCIAL_IMAGES_URL}/spotify-icon.svg`,
    services: {
      listenings: {
        cost: 40,
        amount: 1000,
      },
    },
  },
  ok: {
    // пустой
    name: 'Одноклассники',
    img: `${SOCIAL_IMAGES_URL}/ok-icon.svg`,
    services: {},
  },
  facebook: {
    name: 'Фейсбук',
    img: `${SOCIAL_IMAGES_URL}/facebook-icon.svg`,
    services: {
      followers: {
        cost: 58,
        amount: 1000,
      },
      comments: {
        cost: 3.5,
        amount: 1,
      },
      likes: {
        cost: 55,
        amount: 1000,
      },
    },
  },
  internet: {
    name: 'Интернет',
    img: `${SOCIAL_IMAGES_URL}/internet-icon.svg`,
    services: {
      visitors: {
        cost: 12,
        amount: 1000,
      },
    },
  },
  soundcloud: {
    name: 'Саундклауд',
    img: `${SOCIAL_IMAGES_URL}/soundcloud-icon.svg`,
    services: {
      plays: {
        cost: 6,
        amount: 1000,
      },
      followers: {
        cost: 200,
        amount: 1000,
      },
      comments: {
        cost: 1.2,
        amount: 1,
      },
      likes: {
        cost: 155,
        amount: 1000,
      },
    },
  },
};
